apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-config
  labels:
    app: nginx-config
spec:
  containers:
  - name: nginx
    image: nginx:1.21
    ports:
    - containerPort: 80
    volumeMounts:
    - name: config-volume
      mountPath: /etc/nginx/conf.d
    - name: html-volume
      mountPath: /usr/share/nginx/html
    - name: secret-volume
      mountPath: /etc/secrets
      readOnly: true
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: nginx-secret
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: nginx-secret
          key: password
  volumes:
  - name: config-volume
    configMap:
      name: nginx-config
      items:
      - key: nginx.conf
        path: default.conf
  - name: html-volume
    configMap:
      name: nginx-config
      items:
      - key: index.html
        path: index.html
  - name: secret-volume
    secret:
      secretName: nginx-secret
