apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      queryTimeout: 60s
      timeInterval: 5s

  - name: AWS CloudWatch
    type: cloudwatch
    access: proxy
    url: http://aws-ecs-exporter:9105
    editable: true
    jsonData:
      authType: keys
      defaultRegion: ap-northeast-2

  - name: Google Cloud Monitoring
    type: stackdriver
    access: proxy
    url: http://gcp-cloud-run-exporter:9106
    editable: true
    jsonData:
      authenticationType: jwt
      clientEmail: service-account@project.iam.gserviceaccount.com
      defaultProject: PROJECT_ID
      tokenUri: https://oauth2.googleapis.com/token
